AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: OpenAI compatible API proxy running on AWS Lambda

Parameters:
  FunctionName:
    Type: String
    Default: lambda-llm-proxy
    Description: Name for the Lambda function

Resources:
  openaiProxy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: dist
      Description: 'OpenAI compatible API proxy running on AWS Lambda'
      MemorySize: 128
      Timeout: 120
      Handler: index.handler
      Runtime: nodejs20.x
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowOrigins:
            - '*'
          AllowHeaders:
            - authorization
            - content-type
          AllowMethods:
            - POST
            - GET
          AllowCredentials: true
          MaxAge: 0
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-west-2:0123456789:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:us-west-2:0123456789:log-group:/aws/lambda/openaiProxy:*
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

Outputs:
  FunctionUrl:
    Description: 'Lambda Function URL'
    Value: !Ref openaiProxyUrl
    Export:
      Name: !Sub '${AWS::StackName}-FunctionUrl'
  
  FunctionName:
    Description: 'Lambda Function Name'
    Value: !Ref FunctionName
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'